### ISSUE TITLE
Hello - What's the license of PyNand?

### ISSUE THREAD

**Issue by joaocarvalhoopen** [mossprescott/pynand#36]
Hello Moss Prescott,

A really nice project!

Sometime ago when I was starting to do Nand2Tetris I really like the project but I didn't like the Java tools, they didn't resonate with me.

And at the time I would like to know How I could build all the project in Rust from the simple gates without using there hardware emulator, doing all from start to finish.

But then I come to the conclusion that a logic simulator that can simulate feedback loops isn't as easy at it sounds and the thing stayed that way. Without me doing the simulator in Rust. Only the first steps in Nand2Tetris, but like I said I didn't liked the tools.

Then I tkinkered mentally with the idea of simulating the NAND circuit electrically by simulating the transistors mathematically, even if it was only one logical gate in all the project.

Like allowing the simulation of at least one peace at each level.

And why staying at that level and not learning how to simulate one transistor at a atomic/quantum level? heheheheh It would be really fun to learn all the things about it! And to have at least one component that would work that way.

Then I toyed mentally with the idea that the NAND circuit for a NAND can be made with two transistors one nmos and one pmos and that all the processing of all NAND gates could be made to pass over that two real transistors. With just a control unit made with a Raspberry Pi Pico and the processing of a NAND chopped up into peaces. In with you inject a 3.3V one or a 0V zero and after a delay or instantly you would receive the result of the transistor processing, as a logical value or even as Voltage ADC value.

But currently I'm just interested in knowing what's the license of PyNand to know if it's possible to reimplement it by some kind of translation from Python to Rust.

Thank you for the really good project!

The very best wishes,
João Nuno Carvalho

**Comment by mossprescott** [comment]
Thanks, João! Glad to hear about your excitement and new ideas for this material.

A great thing about the course and the design itself is how it lends itself to being used in new ways. I would be very happy to see my work help inspire a new implementation.

Running a "simulated" CPU on a single pair of transistors is a wild idea. I've toyed with the idea of trying to build something with discrete transistors, but even for the simplest CPU the scale is daunting; it never occurred to me that you could emulate the logic and use just a few components. Very creative! One thing to note: to run a playable Pong, you need to achieve about 1 MHz (that is, one million clock cycles per second for the whole CPU and memory system.) I think that will be challenging with any kind of non-integrated approach (see, for example, https://monster6502.com), but I'm sure you could get it to run some non-interactive programs at a much slower speed. Of course, there are various projects targeting this CPU to FPGAs, but somehow that idea never appealed to me as much.

Unfortunately the license situation is somewhat complicated because this is a semi-"clean room" re-implementation of the "From Nand to Tetris" tools, and this repo also includes tests and example programs that are derived from the course materials. PR #37 makes my own claims clear, but I can't really tell you what the original author's license (GPL) might mean for you if you start with this code. See https://www.nand2tetris.org/software.

Good luck!
